print("'True' is a string literal: ", type("True"))
print(False, end=" ")
print("is a Boolean")
print("(1,2,3) is a tuple ", type((1, 2, 3)))
print("1.5 is a float", type(1.5))
print("[1,2,3] is a list ", type([1, 2, 3]))
print("2 is an int ", type(2))
print("range(5) is a range", type(range(5)))
print("{1,2,3} is a set", type({1, 2, 3}))
print(None, end=" ")
print("is a NoneType", type(None))
print("{'foo': 'bar'} is a dict", type({"foo": "bar"}))
